version: '3'

services:

  cockroachdb:
    image: cockroachdb/cockroach:v2.1.6
    command: start --insecure
    volumes:
      - cockroachdb-data:/var/lib/cockroach
    ports:
      - "26257:26257"
      - "8081:8080"

  accounts-python:
    image: docker-birmingham/accounts-python
    build: ./python
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - DB_URL=cockroachdb

  accounts-quarkus:
    image: docker-birmingham/account-quarkus
    build: ./java
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_URL=cockroachdb

volumes:
  cockroachdb-data:
